services:
  database:
    image: postgres:16.3
    ports:
      - 5432:5432
    environment:
      - DB_DIALECT=postgres
      - DB_PORT=5432
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=senha
      - POSTGRES_DB=courses
    volumes:
      - courses_data:/var/lib/postgresql/data
volumes:
  courses_data:
    driver: local